[features]
seeds = false
skip-lint = false

[programs.localnet]
volswap = "HkmNK58gA3ho7iorsAbHXfTHHLYJ6jenKcZDPDjNknAQ"
funding_swap = "BBnksXi8bg3Z87qdu4neD5LeSY2dgreiABPCeYpvR77u"
exotic_vault = "36pKgauHLWvZDgEs8czCPvyLy8i5mZTD1QXuuCpvcqDV"
shared_oracle = "DyPhNbm845yWMuAmBLmsLANxm7wDJLDwoQNR2n8n8kM1"

[programs.devnet]
volswap = "HkmNK58gA3ho7iorsAbHXfTHHLYJ6jenKcZDPDjNknAQ"
funding_swap = "BBnksXi8bg3Z87qdu4neD5LeSY2dgreiABPCeYpvR77u"
exotic_vault = "36pKgauHLWvZDgEs8czCPvyLy8i5mZTD1QXuuCpvcqDV"
shared_oracle = "DyPhNbm845yWMuAmBLmsLANxm7wDJLDwoQNR2n8n8kM1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
