import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { PublicKey, Keypair, SystemProgram } from "@solana/web3.js";
import { expect } from "chai";
import BN from "bn.js";

// Import the program types (generated by Anchor)
// These will be available after running `anchor build`
type SharedOracle = any; // Will be replaced with actual type

describe("shared-oracle", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  // Program reference - adjust program name as needed
  const program = anchor.workspace.SharedOracle as Program<SharedOracle>;

  const authority = provider.wallet;
  let assetMint: Keypair;
  let priceFeedPDA: PublicKey;
  let sampleBufferPDA: PublicKey;
  let varianceTrackerPDA: PublicKey;

  before(async () => {
    // Create a mock asset mint for testing
    assetMint = Keypair.generate();
  });

  // ============================================================================
  // Price Feed Tests
  // ============================================================================

  describe("Price Feed", () => {
    it("should initialize a price feed", async () => {
      const assetSymbol = "SOL";
      const sampleIntervalSeconds = 60;
      const maxSamples = 1000;

      // Derive PDAs
      [priceFeedPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("price_feed"), assetMint.publicKey.toBuffer()],
        program.programId
      );

      [sampleBufferPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("sample_buffer"), priceFeedPDA.toBuffer()],
        program.programId
      );

      try {
        await program.methods
          .initializePriceFeed(assetSymbol, new BN(sampleIntervalSeconds), maxSamples)
          .accounts({
            authority: authority.publicKey,
            assetMint: assetMint.publicKey,
            priceFeed: priceFeedPDA,
            sampleBuffer: sampleBufferPDA,
            systemProgram: SystemProgram.programId,
          })
          .rpc();

        // Fetch and verify the price feed
        const priceFeed = await program.account.priceFeed.fetch(priceFeedPDA);
        expect(priceFeed.assetSymbol).to.equal(assetSymbol);
        expect(priceFeed.sampleIntervalSeconds.toNumber()).to.equal(sampleIntervalSeconds);
        expect(priceFeed.isActive).to.be.true;
      } catch (e) {
        console.log("Initialize price feed error:", e);
        throw e;
      }
    });

    it("should record a price sample", async () => {
      const price = new BN(100_000_000); // $100 with 6 decimals

      try {
        await program.methods
          .recordPrice(price)
          .accounts({
            authority: authority.publicKey,
            priceFeed: priceFeedPDA,
            sampleBuffer: sampleBufferPDA,
          })
          .rpc();

        // Fetch and verify the price feed was updated
        const priceFeed = await program.account.priceFeed.fetch(priceFeedPDA);
        expect(priceFeed.currentPrice.toNumber()).to.equal(price.toNumber());
      } catch (e) {
        console.log("Record price error:", e);
        throw e;
      }
    });

    it("should update price feed configuration", async () => {
      const newInterval = new BN(120);

      try {
        await program.methods
          .updatePriceFeed(newInterval, null)
          .accounts({
            authority: authority.publicKey,
            priceFeed: priceFeedPDA,
          })
          .rpc();

        const priceFeed = await program.account.priceFeed.fetch(priceFeedPDA);
        expect(priceFeed.sampleIntervalSeconds.toNumber()).to.equal(120);
      } catch (e) {
        console.log("Update price feed error:", e);
        throw e;
      }
    });

    it("should reject unauthorized updates", async () => {
      const unauthorizedUser = Keypair.generate();

      try {
        await program.methods
          .updatePriceFeed(new BN(300), null)
          .accounts({
            authority: unauthorizedUser.publicKey,
            priceFeed: priceFeedPDA,
          })
          .signers([unauthorizedUser])
          .rpc();

        expect.fail("Should have thrown unauthorized error");
      } catch (e: any) {
        expect(e.message).to.include("Unauthorized");
      }
    });
  });

  // ============================================================================
  // Funding Feed Tests
  // ============================================================================

  describe("Funding Feed", () => {
    let fundingFeedPDA: PublicKey;
    const marketSymbol = "SOL-PERP";

    it("should initialize a funding feed", async () => {
      const fundingIntervalSeconds = 28800; // 8 hours

      [fundingFeedPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("funding_feed"), Buffer.from(marketSymbol)],
        program.programId
      );

      try {
        await program.methods
          .initializeFundingFeed(marketSymbol, new BN(fundingIntervalSeconds))
          .accounts({
            authority: authority.publicKey,
            fundingFeed: fundingFeedPDA,
            systemProgram: SystemProgram.programId,
          })
          .rpc();

        const fundingFeed = await program.account.fundingFeed.fetch(fundingFeedPDA);
        expect(fundingFeed.marketSymbol).to.equal(marketSymbol);
        expect(fundingFeed.isActive).to.be.true;
      } catch (e) {
        console.log("Initialize funding feed error:", e);
        throw e;
      }
    });

    it("should record a funding rate", async () => {
      const rateBps = new BN(50); // 0.50% funding rate

      try {
        await program.methods
          .recordFundingRate(rateBps)
          .accounts({
            authority: authority.publicKey,
            fundingFeed: fundingFeedPDA,
          })
          .rpc();

        const fundingFeed = await program.account.fundingFeed.fetch(fundingFeedPDA);
        expect(fundingFeed.currentRateBps.toNumber()).to.equal(50);
      } catch (e) {
        console.log("Record funding rate error:", e);
        throw e;
      }
    });
  });

  // ============================================================================
  // Variance Tracker Tests
  // ============================================================================

  describe("Variance Tracker", () => {
    it("should initialize a variance tracker", async () => {
      const epochDurationSeconds = 604800; // 7 days

      [varianceTrackerPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("variance_tracker"), priceFeedPDA.toBuffer()],
        program.programId
      );

      try {
        await program.methods
          .initializeVarianceTracker(new BN(epochDurationSeconds))
          .accounts({
            authority: authority.publicKey,
            priceFeed: priceFeedPDA,
            varianceTracker: varianceTrackerPDA,
            systemProgram: SystemProgram.programId,
          })
          .rpc();

        const tracker = await program.account.varianceTracker.fetch(varianceTrackerPDA);
        expect(tracker.epochDurationSeconds.toNumber()).to.equal(epochDurationSeconds);
      } catch (e) {
        console.log("Initialize variance tracker error:", e);
        throw e;
      }
    });
  });

  // ============================================================================
  // Volatility Index (SVI) Tests
  // ============================================================================

  describe("Volatility Index", () => {
    let volatilityIndexPDA: PublicKey;
    const indexName = "SVI-SOL-7D";

    it("should initialize a volatility index", async () => {
      const durationDays = 7;
      const impliedWeight = 5000; // 50%

      [volatilityIndexPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("volatility_index"), priceFeedPDA.toBuffer(), Buffer.from(indexName)],
        program.programId
      );

      try {
        await program.methods
          .initializeVolatilityIndex(indexName, durationDays, impliedWeight)
          .accounts({
            authority: authority.publicKey,
            priceFeed: priceFeedPDA,
            varianceTracker: varianceTrackerPDA,
            volatilityIndex: volatilityIndexPDA,
            systemProgram: SystemProgram.programId,
          })
          .rpc();

        const index = await program.account.volatilityIndex.fetch(volatilityIndexPDA);
        expect(index.indexName).to.equal(indexName);
        expect(index.durationDays).to.equal(durationDays);
        expect(index.impliedWeight).to.equal(impliedWeight);
        expect(index.isActive).to.be.true;
      } catch (e) {
        console.log("Initialize volatility index error:", e);
        throw e;
      }
    });

    it("should update the volatility index", async () => {
      try {
        await program.methods
          .updateVolatilityIndex()
          .accounts({
            payer: authority.publicKey,
            volatilityIndex: volatilityIndexPDA,
            varianceTracker: varianceTrackerPDA,
          })
          .rpc();

        const index = await program.account.volatilityIndex.fetch(volatilityIndexPDA);
        // Just verify it didn't error - value depends on variance tracker state
        expect(index.lastUpdate.toNumber()).to.be.greaterThan(0);
      } catch (e) {
        console.log("Update volatility index error:", e);
        throw e;
      }
    });

    it("should set implied volatility", async () => {
      const impliedVol = new BN(4500); // 45% implied vol

      try {
        await program.methods
          .setImpliedVolatility(impliedVol)
          .accounts({
            authority: authority.publicKey,
            volatilityIndex: volatilityIndexPDA,
          })
          .rpc();

        const index = await program.account.volatilityIndex.fetch(volatilityIndexPDA);
        expect(index.impliedVol.toNumber()).to.equal(4500);
      } catch (e) {
        console.log("Set implied volatility error:", e);
        throw e;
      }
    });
  });

  // ============================================================================
  // CEX Funding Feed Tests
  // ============================================================================

  describe("CEX Funding Feed", () => {
    let cexFundingFeedPDA: PublicKey;
    const marketSymbol = "BTC-PERP";

    it("should initialize a CEX funding feed", async () => {
      [cexFundingFeedPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("cex_funding_feed"), Buffer.from(marketSymbol)],
        program.programId
      );

      // Aggregation method enum - 0 = SimpleAverage
      const aggregationMethod = { simpleAverage: {} };

      try {
        await program.methods
          .initializeCexFundingFeed(marketSymbol, aggregationMethod)
          .accounts({
            authority: authority.publicKey,
            cexFundingFeed: cexFundingFeedPDA,
            systemProgram: SystemProgram.programId,
          })
          .rpc();

        const feed = await program.account.cexFundingFeed.fetch(cexFundingFeedPDA);
        expect(feed.marketSymbol).to.equal(marketSymbol);
        expect(feed.isActive).to.be.true;
      } catch (e) {
        console.log("Initialize CEX funding feed error:", e);
        throw e;
      }
    });

    it("should add an exchange source", async () => {
      // Exchange enum - Binance
      const exchange = { binance: {} };
      const fundingInterval = new BN(28800); // 8 hours

      try {
        await program.methods
          .addExchangeSource(exchange, fundingInterval)
          .accounts({
            authority: authority.publicKey,
            cexFundingFeed: cexFundingFeedPDA,
          })
          .rpc();

        const feed = await program.account.cexFundingFeed.fetch(cexFundingFeedPDA);
        expect(feed.exchangeSources.length).to.equal(1);
      } catch (e) {
        console.log("Add exchange source error:", e);
        throw e;
      }
    });

    it("should update exchange funding rate", async () => {
      const exchange = { binance: {} };
      const rateBps = new BN(105); // 0.0105%
      const openInterest = new BN(2_450_000_000_000_000); // $2.45B
      const nextFundingTime = new BN(Date.now() / 1000 + 28800);

      try {
        await program.methods
          .updateExchangeFunding(exchange, rateBps, openInterest, nextFundingTime)
          .accounts({
            authority: authority.publicKey,
            cexFundingFeed: cexFundingFeedPDA,
          })
          .rpc();

        const feed = await program.account.cexFundingFeed.fetch(cexFundingFeedPDA);
        expect(feed.aggregatedRateBps.toNumber()).to.equal(105);
      } catch (e) {
        console.log("Update exchange funding error:", e);
        throw e;
      }
    });
  });

  // ============================================================================
  // Secondary Market Tests
  // ============================================================================

  describe("Secondary Market", () => {
    let secondaryMarketPDA: PublicKey;
    let positionTokenPDA: PublicKey;
    let positionAccount: Keypair;
    const feeRecipient = Keypair.generate();

    it("should initialize a secondary market", async () => {
      // Protocol enum - VolSwap
      const protocol = { volSwap: {} };
      const feeRateBps = 50; // 0.5%

      // VolSwap seed bytes
      const protocolSeedBytes = Buffer.from("volswap_________");

      [secondaryMarketPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("secondary_market"), protocolSeedBytes],
        program.programId
      );

      try {
        await program.methods
          .initializeSecondaryMarket(protocol, feeRateBps)
          .accounts({
            authority: authority.publicKey,
            feeRecipient: feeRecipient.publicKey,
            secondaryMarket: secondaryMarketPDA,
            systemProgram: SystemProgram.programId,
          })
          .rpc();

        const market = await program.account.secondaryMarket.fetch(secondaryMarketPDA);
        expect(market.feeRateBps).to.equal(50);
        expect(market.isActive).to.be.true;
      } catch (e) {
        console.log("Initialize secondary market error:", e);
        throw e;
      }
    });

    it("should tokenize a position", async () => {
      positionAccount = Keypair.generate();
      const protocol = { volSwap: {} };
      const notional = new BN(10_000_000_000); // $10,000
      const expiry = new BN(Date.now() / 1000 + 604800); // 7 days
      const direction = { long: {} };
      const strike = new BN(3500); // 35%
      const positionHash = Buffer.alloc(32, 1); // Dummy hash

      [positionTokenPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("position_token"), positionAccount.publicKey.toBuffer()],
        program.programId
      );

      try {
        await program.methods
          .tokenizePosition(
            protocol,
            notional,
            expiry,
            direction,
            strike,
            Array.from(positionHash)
          )
          .accounts({
            owner: authority.publicKey,
            positionAccount: positionAccount.publicKey,
            positionToken: positionTokenPDA,
            systemProgram: SystemProgram.programId,
          })
          .rpc();

        const token = await program.account.positionToken.fetch(positionTokenPDA);
        expect(token.notional.toNumber()).to.equal(10_000_000_000);
        expect(token.isActive).to.be.true;
        expect(token.isListed).to.be.false;
      } catch (e) {
        console.log("Tokenize position error:", e);
        throw e;
      }
    });

    it("should list a position for sale", async () => {
      const price = new BN(1_500_000_000); // $1,500
      const minPrice = new BN(1_000_000_000); // $1,000 min
      const listingExpiry = new BN(Date.now() / 1000 + 86400); // 1 day

      try {
        await program.methods
          .listPosition(price, minPrice, listingExpiry)
          .accounts({
            owner: authority.publicKey,
            positionToken: positionTokenPDA,
            secondaryMarket: secondaryMarketPDA,
          })
          .rpc();

        const token = await program.account.positionToken.fetch(positionTokenPDA);
        expect(token.isListed).to.be.true;
        expect(token.listingPrice.toNumber()).to.equal(1_500_000_000);
      } catch (e) {
        console.log("List position error:", e);
        throw e;
      }
    });

    it("should cancel a listing", async () => {
      try {
        await program.methods
          .cancelListing()
          .accounts({
            owner: authority.publicKey,
            positionToken: positionTokenPDA,
            secondaryMarket: secondaryMarketPDA,
          })
          .rpc();

        const token = await program.account.positionToken.fetch(positionTokenPDA);
        expect(token.isListed).to.be.false;
        expect(token.listingPrice.toNumber()).to.equal(0);
      } catch (e) {
        console.log("Cancel listing error:", e);
        throw e;
      }
    });

    it("should buy a listed position", async () => {
      // First, list the position again
      const price = new BN(1_500_000_000);
      const minPrice = new BN(1_000_000_000);
      const listingExpiry = new BN(Date.now() / 1000 + 86400);

      await program.methods
        .listPosition(price, minPrice, listingExpiry)
        .accounts({
          owner: authority.publicKey,
          positionToken: positionTokenPDA,
          secondaryMarket: secondaryMarketPDA,
        })
        .rpc();

      // Now buy with a different user
      const buyer = Keypair.generate();

      // Airdrop some SOL to buyer for transaction fees
      const signature = await provider.connection.requestAirdrop(
        buyer.publicKey,
        1_000_000_000
      );
      await provider.connection.confirmTransaction(signature);

      try {
        await program.methods
          .buyPosition()
          .accounts({
            buyer: buyer.publicKey,
            positionToken: positionTokenPDA,
            secondaryMarket: secondaryMarketPDA,
          })
          .signers([buyer])
          .rpc();

        const token = await program.account.positionToken.fetch(positionTokenPDA);
        expect(token.isListed).to.be.false;
        expect(token.owner.toString()).to.equal(buyer.publicKey.toString());

        const market = await program.account.secondaryMarket.fetch(secondaryMarketPDA);
        expect(market.totalTrades.toNumber()).to.equal(1);
      } catch (e) {
        console.log("Buy position error:", e);
        throw e;
      }
    });
  });
});
