import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { PublicKey, Keypair, SystemProgram } from "@solana/web3.js";
import { expect } from "chai";
import BN from "bn.js";

// Import the program types (generated by Anchor)
// These will be available after running `anchor build`
type SharedOracle = any; // Will be replaced with actual type

describe("shared-oracle", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  // Program reference - adjust program name as needed
  const program = anchor.workspace.SharedOracle as Program<SharedOracle>;

  const authority = provider.wallet;
  let assetMint: Keypair;
  let priceFeedPDA: PublicKey;
  let sampleBufferPDA: PublicKey;
  let varianceTrackerPDA: PublicKey;

  before(async () => {
    // Create a mock asset mint for testing
    assetMint = Keypair.generate();
  });

  // ============================================================================
  // Price Feed Tests
  // ============================================================================

  describe("Price Feed", () => {
    it("should initialize a price feed", async () => {
      const assetSymbol = "SOL";
      const sampleIntervalSeconds = 1;
      const maxSamples = 360;

      // Derive PDAs
      [priceFeedPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("price_feed"), assetMint.publicKey.toBuffer()],
        program.programId
      );

      [sampleBufferPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("sample_buffer"), priceFeedPDA.toBuffer()],
        program.programId
      );

      try {
        await program.methods
          .initializePriceFeed(assetSymbol, new BN(sampleIntervalSeconds), maxSamples)
          .accounts({
            authority: authority.publicKey,
            assetMint: assetMint.publicKey,
            priceFeed: priceFeedPDA,
            sampleBuffer: sampleBufferPDA,
            systemProgram: SystemProgram.programId,
          })
          .rpc();

        // Fetch and verify the price feed
        const priceFeed = await program.account.priceFeed.fetch(priceFeedPDA);
        expect(priceFeed.assetSymbol).to.equal(assetSymbol);
        expect(priceFeed.sampleIntervalSeconds.toNumber()).to.equal(sampleIntervalSeconds);
        expect(priceFeed.isActive).to.be.true;
      } catch (e) {
        console.log("Initialize price feed error:", e);
        throw e;
      }
    });

    it("should record a price sample", async () => {
      const price = new BN(100_000_000); // $100 with 6 decimals

      try {
        await program.methods
          .recordPrice(price)
          .accounts({
            authority: authority.publicKey,
            priceFeed: priceFeedPDA,
            sampleBuffer: sampleBufferPDA,
          })
          .rpc();

        // Fetch and verify the price feed was updated
        const priceFeed = await program.account.priceFeed.fetch(priceFeedPDA);
        expect(priceFeed.lastPrice.toNumber()).to.equal(price.toNumber());
      } catch (e) {
        console.log("Record price error:", e);
        throw e;
      }
    });

    it("should update price feed configuration", async () => {
      const newInterval = new BN(120);

      try {
        await program.methods
          .updatePriceFeed(newInterval, null)
          .accounts({
            authority: authority.publicKey,
            priceFeed: priceFeedPDA,
          })
          .rpc();

        const priceFeed = await program.account.priceFeed.fetch(priceFeedPDA);
        expect(priceFeed.sampleIntervalSeconds.toNumber()).to.equal(120);
      } catch (e) {
        console.log("Update price feed error:", e);
        throw e;
      }
    });

    it("should reject unauthorized updates", async () => {
      const unauthorizedUser = Keypair.generate();

      try {
        await program.methods
          .updatePriceFeed(new BN(300), null)
          .accounts({
            authority: unauthorizedUser.publicKey,
            priceFeed: priceFeedPDA,
          })
          .signers([unauthorizedUser])
          .rpc();

        expect.fail("Should have thrown unauthorized error");
      } catch (e: any) {
        expect(e.message).to.include("Unauthorized");
      }
    });
  });

  // ============================================================================
  // Circuit Breaker Tests
  // ============================================================================

  describe("Circuit Breaker", () => {
    let cbAssetMint: Keypair;
    let cbPriceFeedPDA: PublicKey;
    let cbSampleBufferPDA: PublicKey;

    before(async () => {
      cbAssetMint = Keypair.generate();

      [cbPriceFeedPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("price_feed"), cbAssetMint.publicKey.toBuffer()],
        program.programId
      );

      [cbSampleBufferPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("sample_buffer"), cbPriceFeedPDA.toBuffer()],
        program.programId
      );

      // Initialize a new price feed for circuit breaker testing
      // Use 1-second interval so tests don't need 60s waits
      await program.methods
        .initializePriceFeed("CB-TEST", new BN(1), 360)
        .accounts({
          authority: authority.publicKey,
          assetMint: cbAssetMint.publicKey,
          priceFeed: cbPriceFeedPDA,
          sampleBuffer: cbSampleBufferPDA,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      // Record an initial price to establish baseline
      await program.methods
        .recordPrice(new BN(100_000_000)) // $100
        .accounts({
          authority: authority.publicKey,
          priceFeed: cbPriceFeedPDA,
          sampleBuffer: cbSampleBufferPDA,
        })
        .rpc();
    });

    it("should configure circuit breaker threshold", async () => {
      const maxDeviationBps = 1000; // 10% max deviation

      await program.methods
        .configureCircuitBreaker(maxDeviationBps)
        .accounts({
          authority: authority.publicKey,
          priceFeed: cbPriceFeedPDA,
        })
        .rpc();

      const priceFeed = await program.account.priceFeed.fetch(cbPriceFeedPDA);
      expect(priceFeed.maxDeviationBps).to.equal(1000);
      expect(priceFeed.isCircuitBroken).to.be.false;
    });

    it("should accept price within deviation threshold", async () => {
      // Wait for sample interval
      await new Promise((resolve) => setTimeout(resolve, 2000));

      // Record a price within 10% of $100 -> $105
      await program.methods
        .recordPrice(new BN(105_000_000))
        .accounts({
          authority: authority.publicKey,
          priceFeed: cbPriceFeedPDA,
          sampleBuffer: cbSampleBufferPDA,
        })
        .rpc();

      const priceFeed = await program.account.priceFeed.fetch(cbPriceFeedPDA);
      expect(priceFeed.lastPrice.toNumber()).to.equal(105_000_000);
      expect(priceFeed.isCircuitBroken).to.be.false;
    });

    it("should trigger circuit breaker on large deviation", async () => {
      await new Promise((resolve) => setTimeout(resolve, 2000));

      // Record a price with >10% deviation: $105 -> $120 (14.3% deviation)
      // Transaction succeeds but circuit breaker flag is set and price is NOT recorded
      await program.methods
        .recordPrice(new BN(120_000_000))
        .accounts({
          authority: authority.publicKey,
          priceFeed: cbPriceFeedPDA,
          sampleBuffer: cbSampleBufferPDA,
        })
        .rpc();

      // Verify feed is now paused and price was NOT updated
      const priceFeed = await program.account.priceFeed.fetch(cbPriceFeedPDA);
      expect(priceFeed.isCircuitBroken).to.be.true;
      expect(priceFeed.circuitBreakTimestamp.toNumber()).to.be.greaterThan(0);
      expect(priceFeed.lastPrice.toNumber()).to.equal(105_000_000); // Unchanged
    });

    it("should reject all price updates while circuit broken", async () => {
      await new Promise((resolve) => setTimeout(resolve, 2000));

      try {
        await program.methods
          .recordPrice(new BN(106_000_000))
          .accounts({
            authority: authority.publicKey,
            priceFeed: cbPriceFeedPDA,
            sampleBuffer: cbSampleBufferPDA,
          })
          .rpc();

        expect.fail("Should have rejected while circuit broken");
      } catch (e: any) {
        expect(e.message).to.include("FeedCircuitBroken");
      }
    });

    it("should reset circuit breaker with new baseline price", async () => {
      const newValidPrice = new BN(118_000_000); // Set new baseline to $118

      await program.methods
        .resetCircuitBreaker(newValidPrice)
        .accounts({
          authority: authority.publicKey,
          priceFeed: cbPriceFeedPDA,
        })
        .rpc();

      const priceFeed = await program.account.priceFeed.fetch(cbPriceFeedPDA);
      expect(priceFeed.isCircuitBroken).to.be.false;
      expect(priceFeed.lastValidPrice.toNumber()).to.equal(118_000_000);
    });

    it("should accept prices again after reset", async () => {
      await new Promise((resolve) => setTimeout(resolve, 2000));

      // Record price within 10% of new baseline ($118): $125 (5.9% deviation)
      await program.methods
        .recordPrice(new BN(125_000_000))
        .accounts({
          authority: authority.publicKey,
          priceFeed: cbPriceFeedPDA,
          sampleBuffer: cbSampleBufferPDA,
        })
        .rpc();

      const priceFeed = await program.account.priceFeed.fetch(cbPriceFeedPDA);
      expect(priceFeed.lastPrice.toNumber()).to.equal(125_000_000);
      expect(priceFeed.isCircuitBroken).to.be.false;
    });

    it("should reject unauthorized circuit breaker reset", async () => {
      const unauthorizedUser = Keypair.generate();

      try {
        await program.methods
          .resetCircuitBreaker(null)
          .accounts({
            authority: unauthorizedUser.publicKey,
            priceFeed: cbPriceFeedPDA,
          })
          .signers([unauthorizedUser])
          .rpc();

        expect.fail("Should have rejected unauthorized reset");
      } catch (e: any) {
        expect(e.message).to.include("Unauthorized");
      }
    });
  });

  // ============================================================================
  // Switchboard Configuration Tests
  // ============================================================================

  describe("Switchboard Configuration", () => {
    it("should set a Switchboard feed on a price feed", async () => {
      const mockSwitchboardFeed = Keypair.generate().publicKey;

      await program.methods
        .setSwitchboardFeed(mockSwitchboardFeed)
        .accounts({
          authority: authority.publicKey,
          priceFeed: priceFeedPDA,
        })
        .rpc();

      const priceFeed = await program.account.priceFeed.fetch(priceFeedPDA);
      expect(priceFeed.switchboardFeed.toString()).to.equal(mockSwitchboardFeed.toString());
    });

    it("should clear a Switchboard feed", async () => {
      await program.methods
        .setSwitchboardFeed(null)
        .accounts({
          authority: authority.publicKey,
          priceFeed: priceFeedPDA,
        })
        .rpc();

      const priceFeed = await program.account.priceFeed.fetch(priceFeedPDA);
      expect(priceFeed.switchboardFeed).to.be.null;
    });

    it("should reject unauthorized Switchboard feed updates", async () => {
      const unauthorizedUser = Keypair.generate();
      const mockFeed = Keypair.generate().publicKey;

      try {
        await program.methods
          .setSwitchboardFeed(mockFeed)
          .accounts({
            authority: unauthorizedUser.publicKey,
            priceFeed: priceFeedPDA,
          })
          .signers([unauthorizedUser])
          .rpc();

        expect.fail("Should have rejected unauthorized update");
      } catch (e: any) {
        expect(e.message).to.include("Unauthorized");
      }
    });
  });

  // ============================================================================
  // Funding Feed Tests
  // ============================================================================

  describe("Funding Feed", () => {
    let fundingFeedPDA: PublicKey;
    const marketSymbol = "ETH-PERP";

    it("should initialize a funding feed", async () => {
      const fundingIntervalSeconds = 28800; // 8 hours

      [fundingFeedPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("funding_feed"), Buffer.from(marketSymbol)],
        program.programId
      );

      try {
        await program.methods
          .initializeFundingFeed(marketSymbol, new BN(fundingIntervalSeconds))
          .accounts({
            authority: authority.publicKey,
            fundingFeed: fundingFeedPDA,
            systemProgram: SystemProgram.programId,
          })
          .rpc();

        const fundingFeed = await program.account.fundingFeed.fetch(fundingFeedPDA);
        expect(fundingFeed.marketSymbol).to.equal(marketSymbol);
        expect(fundingFeed.isActive).to.be.true;
      } catch (e) {
        console.log("Initialize funding feed error:", e);
        throw e;
      }
    });

    it("should record a funding rate", async () => {
      const rateBps = new BN(50); // 0.50% funding rate

      try {
        await program.methods
          .recordFundingRate(rateBps)
          .accounts({
            authority: authority.publicKey,
            fundingFeed: fundingFeedPDA,
          })
          .rpc();

        const fundingFeed = await program.account.fundingFeed.fetch(fundingFeedPDA);
        expect(fundingFeed.currentRateBps.toNumber()).to.equal(50);
      } catch (e) {
        console.log("Record funding rate error:", e);
        throw e;
      }
    });
  });

  // ============================================================================
  // Variance Tracker Tests
  // ============================================================================

  describe("Variance Tracker", () => {
    it("should initialize a variance tracker", async () => {
      const epochDurationSeconds = 604800; // 7 days

      [varianceTrackerPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("variance_tracker"), priceFeedPDA.toBuffer()],
        program.programId
      );

      try {
        await program.methods
          .initializeVarianceTracker(new BN(epochDurationSeconds))
          .accounts({
            authority: authority.publicKey,
            priceFeed: priceFeedPDA,
            varianceTracker: varianceTrackerPDA,
            systemProgram: SystemProgram.programId,
          })
          .rpc();

        const tracker = await program.account.varianceTracker.fetch(varianceTrackerPDA);
        expect(tracker.epochDurationSeconds.toNumber()).to.equal(epochDurationSeconds);
      } catch (e) {
        console.log("Initialize variance tracker error:", e);
        throw e;
      }
    });
  });

  // ============================================================================
  // Volatility Index (SVI) Tests
  // ============================================================================

  describe("Volatility Index", () => {
    let volatilityIndexPDA: PublicKey;
    const indexName = "SVI-SOL-7D";

    it("should initialize a volatility index", async () => {
      const durationDays = 7;
      const impliedWeight = 5000; // 50%

      [volatilityIndexPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("volatility_index"), priceFeedPDA.toBuffer(), Buffer.from(indexName)],
        program.programId
      );

      try {
        await program.methods
          .initializeVolatilityIndex(indexName, durationDays, impliedWeight)
          .accounts({
            authority: authority.publicKey,
            priceFeed: priceFeedPDA,
            varianceTracker: varianceTrackerPDA,
            volatilityIndex: volatilityIndexPDA,
            systemProgram: SystemProgram.programId,
          })
          .rpc();

        const index = await program.account.volatilityIndex.fetch(volatilityIndexPDA);
        expect(index.indexName).to.equal(indexName);
        expect(index.durationDays).to.equal(durationDays);
        expect(index.impliedWeight).to.equal(impliedWeight);
        expect(index.isActive).to.be.true;
      } catch (e) {
        console.log("Initialize volatility index error:", e);
        throw e;
      }
    });

    it("should update the volatility index", async () => {
      try {
        await program.methods
          .updateVolatilityIndex()
          .accounts({
            payer: authority.publicKey,
            volatilityIndex: volatilityIndexPDA,
            varianceTracker: varianceTrackerPDA,
          })
          .rpc();

        const index = await program.account.volatilityIndex.fetch(volatilityIndexPDA);
        // Just verify it didn't error - value depends on variance tracker state
        expect(index.lastUpdate.toNumber()).to.be.greaterThan(0);
      } catch (e) {
        console.log("Update volatility index error:", e);
        throw e;
      }
    });

    it("should set implied volatility", async () => {
      const impliedVol = new BN(4500); // 45% implied vol

      try {
        await program.methods
          .setImpliedVolatility(impliedVol)
          .accounts({
            authority: authority.publicKey,
            volatilityIndex: volatilityIndexPDA,
          })
          .rpc();

        const index = await program.account.volatilityIndex.fetch(volatilityIndexPDA);
        expect(index.impliedVol.toNumber()).to.equal(4500);
      } catch (e) {
        console.log("Set implied volatility error:", e);
        throw e;
      }
    });
  });

  // ============================================================================
  // CEX Funding Feed Tests
  // ============================================================================

  describe("CEX Funding Feed", () => {
    let cexFundingFeedPDA: PublicKey;
    const marketSymbol = "BTC-PERP";

    it("should initialize a CEX funding feed", async () => {
      [cexFundingFeedPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("cex_funding_feed"), Buffer.from(marketSymbol)],
        program.programId
      );

      // Aggregation method enum - Mean variant
      const aggregationMethod = { mean: {} };

      try {
        await program.methods
          .initializeCexFundingFeed(marketSymbol, aggregationMethod)
          .accounts({
            authority: authority.publicKey,
            cexFundingFeed: cexFundingFeedPDA,
            systemProgram: SystemProgram.programId,
          })
          .rpc();

        const feed = await program.account.cexFundingFeed.fetch(cexFundingFeedPDA);
        expect(feed.marketSymbol).to.equal(marketSymbol);
        expect(feed.isActive).to.be.true;
      } catch (e) {
        console.log("Initialize CEX funding feed error:", e);
        throw e;
      }
    });

    it("should add an exchange source", async () => {
      // Exchange enum - Binance
      const exchange = { binance: {} };
      const fundingInterval = new BN(28800); // 8 hours

      try {
        await program.methods
          .addExchangeSource(exchange, fundingInterval)
          .accounts({
            authority: authority.publicKey,
            cexFundingFeed: cexFundingFeedPDA,
          })
          .rpc();

        const feed = await program.account.cexFundingFeed.fetch(cexFundingFeedPDA);
        expect(feed.exchangeSources.length).to.equal(1);
      } catch (e) {
        console.log("Add exchange source error:", e);
        throw e;
      }
    });

    it("should update exchange funding rate", async () => {
      const exchange = { binance: {} };
      const rateBps = new BN(105); // 0.0105%
      const openInterest = new BN(2_450_000_000_000_000); // $2.45B
      const nextFundingTime = new BN(Date.now() / 1000 + 28800);

      try {
        await program.methods
          .updateExchangeFunding(exchange, rateBps, openInterest, nextFundingTime)
          .accounts({
            authority: authority.publicKey,
            cexFundingFeed: cexFundingFeedPDA,
          })
          .rpc();

        const feed = await program.account.cexFundingFeed.fetch(cexFundingFeedPDA);
        expect(feed.aggregatedRateBps.toNumber()).to.equal(105);
      } catch (e) {
        console.log("Update exchange funding error:", e);
        throw e;
      }
    });
  });

  // ============================================================================
  // Secondary Market Tests
  // ============================================================================

  describe("Secondary Market", () => {
    let secondaryMarketPDA: PublicKey;
    let positionTokenPDA: PublicKey;
    let positionAccount: Keypair;
    const feeRecipient = Keypair.generate();

    it("should initialize a secondary market", async () => {
      // Protocol enum - VolSwap
      const protocol = { volSwap: {} };
      const feeRateBps = 50; // 0.5%

      // VolSwap seed bytes
      const protocolSeedBytes = Buffer.from("volswap_________");

      [secondaryMarketPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("secondary_market"), protocolSeedBytes],
        program.programId
      );

      try {
        await program.methods
          .initializeSecondaryMarket(protocol, feeRateBps)
          .accounts({
            authority: authority.publicKey,
            feeRecipient: feeRecipient.publicKey,
            secondaryMarket: secondaryMarketPDA,
            systemProgram: SystemProgram.programId,
          })
          .rpc();

        const market = await program.account.secondaryMarket.fetch(secondaryMarketPDA);
        expect(market.feeRateBps).to.equal(50);
        expect(market.isActive).to.be.true;
      } catch (e) {
        console.log("Initialize secondary market error:", e);
        throw e;
      }
    });

    it("should tokenize a position", async () => {
      positionAccount = Keypair.generate();
      const protocol = { volSwap: {} };
      const notional = new BN(10_000_000_000); // $10,000
      const expiry = new BN(Date.now() / 1000 + 604800); // 7 days
      const direction = { long: {} };
      const strike = new BN(3500); // 35%
      const positionHash = Buffer.alloc(32, 1); // Dummy hash

      [positionTokenPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("position_token"), positionAccount.publicKey.toBuffer()],
        program.programId
      );

      try {
        await program.methods
          .tokenizePosition(
            protocol,
            notional,
            expiry,
            direction,
            strike,
            Array.from(positionHash)
          )
          .accounts({
            owner: authority.publicKey,
            positionAccount: positionAccount.publicKey,
            positionToken: positionTokenPDA,
            systemProgram: SystemProgram.programId,
          })
          .rpc();

        const token = await program.account.positionToken.fetch(positionTokenPDA);
        expect(token.notional.toNumber()).to.equal(10_000_000_000);
        expect(token.isActive).to.be.true;
        expect(token.isListed).to.be.false;
      } catch (e) {
        console.log("Tokenize position error:", e);
        throw e;
      }
    });

    it("should list a position for sale", async () => {
      const price = new BN(1_500_000_000); // $1,500
      const minPrice = new BN(1_000_000_000); // $1,000 min
      const listingExpiry = new BN(Date.now() / 1000 + 86400); // 1 day

      try {
        await program.methods
          .listPosition(price, minPrice, listingExpiry)
          .accounts({
            owner: authority.publicKey,
            positionToken: positionTokenPDA,
            secondaryMarket: secondaryMarketPDA,
          })
          .rpc();

        const token = await program.account.positionToken.fetch(positionTokenPDA);
        expect(token.isListed).to.be.true;
        expect(token.listingPrice.toNumber()).to.equal(1_500_000_000);
      } catch (e) {
        console.log("List position error:", e);
        throw e;
      }
    });

    it("should cancel a listing", async () => {
      try {
        await program.methods
          .cancelListing()
          .accounts({
            owner: authority.publicKey,
            positionToken: positionTokenPDA,
            secondaryMarket: secondaryMarketPDA,
          })
          .rpc();

        const token = await program.account.positionToken.fetch(positionTokenPDA);
        expect(token.isListed).to.be.false;
        expect(token.listingPrice.toNumber()).to.equal(0);
      } catch (e) {
        console.log("Cancel listing error:", e);
        throw e;
      }
    });

    it("should buy a listed position", async () => {
      // First, list the position again
      const price = new BN(1_500_000_000);
      const minPrice = new BN(1_000_000_000);
      const listingExpiry = new BN(Date.now() / 1000 + 86400);

      await program.methods
        .listPosition(price, minPrice, listingExpiry)
        .accounts({
          owner: authority.publicKey,
          positionToken: positionTokenPDA,
          secondaryMarket: secondaryMarketPDA,
        })
        .rpc();

      // Now buy with a different user
      const buyer = Keypair.generate();

      // Airdrop some SOL to buyer for transaction fees
      const signature = await provider.connection.requestAirdrop(
        buyer.publicKey,
        1_000_000_000
      );
      await provider.connection.confirmTransaction(signature);

      try {
        await program.methods
          .buyPosition()
          .accounts({
            buyer: buyer.publicKey,
            positionToken: positionTokenPDA,
            secondaryMarket: secondaryMarketPDA,
          })
          .signers([buyer])
          .rpc();

        const token = await program.account.positionToken.fetch(positionTokenPDA);
        expect(token.isListed).to.be.false;
        expect(token.owner.toString()).to.equal(buyer.publicKey.toString());

        const market = await program.account.secondaryMarket.fetch(secondaryMarketPDA);
        expect(market.totalTrades.toNumber()).to.equal(1);
      } catch (e) {
        console.log("Buy position error:", e);
        throw e;
      }
    });
  });

  // ============================================================================
  // Event Emission Tests
  // ============================================================================

  describe("Event Emission", () => {
    // Dedicated accounts for event emission tests to avoid conflicts
    // with prior test state (e.g. circuit breaker already tripped).
    let evtAssetMint: Keypair;
    let evtPriceFeedPDA: PublicKey;
    let evtSampleBufferPDA: PublicKey;

    before(async () => {
      evtAssetMint = Keypair.generate();

      [evtPriceFeedPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("price_feed"), evtAssetMint.publicKey.toBuffer()],
        program.programId
      );

      [evtSampleBufferPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("sample_buffer"), evtPriceFeedPDA.toBuffer()],
        program.programId
      );
    });

    it("should emit PriceFeedInitialized on initialize (467ms)", async () => {
      await program.methods
        .initializePriceFeed("EVT-SOL", new BN(1), 360)
        .accounts({
          authority: authority.publicKey,
          assetMint: evtAssetMint.publicKey,
          priceFeed: evtPriceFeedPDA,
          sampleBuffer: evtSampleBufferPDA,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      // If tx succeeds, event was emitted (emit! is in the handler)
      // Verify state to confirm handler ran fully
      const feed = await program.account.priceFeed.fetch(evtPriceFeedPDA);
      expect(feed.assetSymbol).to.equal("EVT-SOL");
      expect(feed.authority.toString()).to.equal(authority.publicKey.toString());
    });

    it("should emit PriceRecorded on record_price", async () => {
      const price = new BN(50_000_000); // $50

      await program.methods
        .recordPrice(price)
        .accounts({
          authority: authority.publicKey,
          priceFeed: evtPriceFeedPDA,
          sampleBuffer: evtSampleBufferPDA,
        })
        .rpc();

      // Verify state — emit! runs right before Ok(())
      const feed = await program.account.priceFeed.fetch(evtPriceFeedPDA);
      expect(feed.lastValidPrice.toNumber()).to.equal(50_000_000);
      expect(feed.sampleCount).to.be.greaterThan(0);
    });

    it("should emit CircuitBreakerReset on reset", async () => {
      // Configure circuit breaker with a tight threshold
      await program.methods
        .configureCircuitBreaker(500) // 5% max deviation
        .accounts({
          authority: authority.publicKey,
          priceFeed: evtPriceFeedPDA,
        })
        .rpc();

      // Wait for sample interval
      await new Promise((resolve) => setTimeout(resolve, 2000));

      // Trigger circuit breaker with a large price deviation (>5%)
      await program.methods
        .recordPrice(new BN(60_000_000)) // $60, a 20% jump from $50
        .accounts({
          authority: authority.publicKey,
          priceFeed: evtPriceFeedPDA,
          sampleBuffer: evtSampleBufferPDA,
        })
        .rpc();

      // Verify circuit breaker is tripped
      const feedBefore = await program.account.priceFeed.fetch(evtPriceFeedPDA);
      expect(feedBefore.isCircuitBroken).to.be.true;

      // Now reset — emit! fires in the handler
      await program.methods
        .resetCircuitBreaker(new BN(55_000_000))
        .accounts({
          authority: authority.publicKey,
          priceFeed: evtPriceFeedPDA,
        })
        .rpc();

      // Verify state to confirm handler (and emit!) ran fully
      const feedAfter = await program.account.priceFeed.fetch(evtPriceFeedPDA);
      expect(feedAfter.isCircuitBroken).to.be.false;
      expect(feedAfter.lastValidPrice.toNumber()).to.equal(55_000_000);
    });

    it("should emit FundingRateRecorded on record_funding_rate", async () => {
      const evtMarketSymbol = "EVT-PERP";

      const [evtFundingFeedPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("funding_feed"), Buffer.from(evtMarketSymbol)],
        program.programId
      );

      // Initialize funding feed
      await program.methods
        .initializeFundingFeed(evtMarketSymbol, new BN(28800))
        .accounts({
          authority: authority.publicKey,
          fundingFeed: evtFundingFeedPDA,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      // Record a funding rate — emit! fires in the handler
      await program.methods
        .recordFundingRate(new BN(75))
        .accounts({
          authority: authority.publicKey,
          fundingFeed: evtFundingFeedPDA,
        })
        .rpc();

      // Verify state to confirm handler ran fully
      const feed = await program.account.fundingFeed.fetch(evtFundingFeedPDA);
      expect(feed.currentRateBps.toNumber()).to.equal(75);
      expect(feed.totalPeriods.toNumber()).to.be.greaterThan(0);
    });

    it("should emit PositionListed on list_position", async () => {
      // Create fresh position and market for event tests
      const evtPositionAccount = Keypair.generate();
      const protocol = { volSwap: {} };
      const protocolSeedBytes = Buffer.from("volswap_________");

      const [evtSecondaryMarketPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("secondary_market"), protocolSeedBytes],
        program.programId
      );

      const [evtPositionTokenPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("position_token"), evtPositionAccount.publicKey.toBuffer()],
        program.programId
      );

      // Tokenize a position
      const notional = new BN(5_000_000_000);
      const expiry = new BN(Date.now() / 1000 + 604800);
      const direction = { long: {} };
      const strike = new BN(4000);
      const positionHash = Buffer.alloc(32, 2);

      await program.methods
        .tokenizePosition(protocol, notional, expiry, direction, strike, Array.from(positionHash))
        .accounts({
          owner: authority.publicKey,
          positionAccount: evtPositionAccount.publicKey,
          positionToken: evtPositionTokenPDA,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      // List the position — emit! fires in the handler
      const price = new BN(2_000_000_000);
      const minPrice = new BN(1_500_000_000);
      const listingExpiry = new BN(Date.now() / 1000 + 86400);

      await program.methods
        .listPosition(price, minPrice, listingExpiry)
        .accounts({
          owner: authority.publicKey,
          positionToken: evtPositionTokenPDA,
          secondaryMarket: evtSecondaryMarketPDA,
        })
        .rpc();

      // Verify state to confirm handler ran fully
      const token = await program.account.positionToken.fetch(evtPositionTokenPDA);
      expect(token.isListed).to.be.true;
      expect(token.listingPrice.toNumber()).to.equal(2_000_000_000);
    });

    it("should emit PositionSold on buy_position", async () => {
      // Create another fresh position for the buy test
      const evtPositionAccount2 = Keypair.generate();
      const protocol = { volSwap: {} };
      const protocolSeedBytes = Buffer.from("volswap_________");

      const [evtSecondaryMarketPDA] = PublicKey.findProgramAddressSync(
        [Buffer.from("secondary_market"), protocolSeedBytes],
        program.programId
      );

      const [evtPositionTokenPDA2] = PublicKey.findProgramAddressSync(
        [Buffer.from("position_token"), evtPositionAccount2.publicKey.toBuffer()],
        program.programId
      );

      // Tokenize
      const notional = new BN(3_000_000_000);
      const expiry = new BN(Date.now() / 1000 + 604800);
      const direction = { long: {} };
      const strike = new BN(3000);
      const positionHash = Buffer.alloc(32, 3);

      await program.methods
        .tokenizePosition(protocol, notional, expiry, direction, strike, Array.from(positionHash))
        .accounts({
          owner: authority.publicKey,
          positionAccount: evtPositionAccount2.publicKey,
          positionToken: evtPositionTokenPDA2,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      // List the position
      const price = new BN(1_000_000_000);
      const minPrice = new BN(800_000_000);
      const listingExpiry = new BN(Date.now() / 1000 + 86400);

      await program.methods
        .listPosition(price, minPrice, listingExpiry)
        .accounts({
          owner: authority.publicKey,
          positionToken: evtPositionTokenPDA2,
          secondaryMarket: evtSecondaryMarketPDA,
        })
        .rpc();

      // Create a buyer and airdrop SOL
      const buyer = Keypair.generate();
      const airdropSig = await provider.connection.requestAirdrop(
        buyer.publicKey,
        1_000_000_000
      );
      await provider.connection.confirmTransaction(airdropSig);

      // Buy — emit! fires in the handler
      await program.methods
        .buyPosition()
        .accounts({
          buyer: buyer.publicKey,
          positionToken: evtPositionTokenPDA2,
          secondaryMarket: evtSecondaryMarketPDA,
        })
        .signers([buyer])
        .rpc();

      // Verify state to confirm handler ran fully
      const token = await program.account.positionToken.fetch(evtPositionTokenPDA2);
      expect(token.owner.toString()).to.equal(buyer.publicKey.toString());
      expect(token.isListed).to.be.false;
    });
  });
});
