[package]
name = "volswap"
version = "0.1.0"
description = "Variance Swaps & Volatility Index Protocol"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "volswap"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.30.1", features = ["init-if-needed"] }
shared-oracle = { path = "../shared-oracle", features = ["cpi"] }
spl-token = { version = "3.5", features = ["no-entrypoint"] }
